replicaCount: 1
image:
  repository: ben14132/java-app-5
  pullPolicy: IfNotPresent
  tag: java-app-5-dev-latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: 
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
  prometheus.io/path: "/actuator/prometheus"
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8081
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: java-app-5-dev.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
serviceMonitor: 
  enabled: true
  additionalLabels:
    release: prometheus
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
